version: 2

before:
  hooks:
    - go mod tidy
builds:
  - 
    id: "sync"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}-
      {{- tolower .Os }}-
      {{- tolower .Arch }}

kos:
  - repositories: 
      - ghcr.io/juev/sync
    build: "sync"
    tags:
      - "{{.Tag}}"
      - latest
    base_image: alpine:latest
    user: "1001:1001"
    bare: true
    preserve_import_paths: false
    platforms:
      - linux/amd64
      - linux/arm64

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^Merge pull'